apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: route
spec:
  replicas: 1
  selector:
    matchLabels:
      name: route-web
      micro: service
  template:
    metadata:
      labels:
        name: route-web
        micro: service
    spec:
      containers:
        - name: route
          command: [
		"/route-web",
	  ]
          image: 10.9.19.140/test/route-web
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: route-port
          env:
          - name: MICRO_SERVER_ADDRESS
            value: "0.0.0.0:8080"
          - name: MICRO_BROKER
            value: "nats"
          - name: MICRO_BROKER_ADDRESS
            value: "nats-cluster"
          - name: MICRO_REGISTRY
            value: "etcd"
          - name: MICRO_REGISTRY_ADDRESS
            value: "etcd-cluster-client"
        - name: health
          command: [
        "/health",
        "--health_address=0.0.0.0:8081",
		"--server_name=tpush.web.route",
		"--server_address=0.0.0.0:8080"
	  ]
          image: 10.9.19.140/test/health
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3

